import type { FAQItemData, Opinion, Project } from './types';

export const faqsData: FAQItemData[] = [
  { q: "Jak długo trwa wykonanie hydroizolacji dachu?", a: "Większość standardowych dachów domów jednorodzinnych zabezpieczamy w 1-2 dni. W przypadku dużych hal przemysłowych czas realizacji zależy od metrażu, ale dzięki metodzie natryskowej jest on zaledwie ułamkiem tego, co przy użyciu tradycyjnej papy termozgrzewalnej." },
  { q: "Czy dajecie gwarancję na szczelność dachu?", a: "Oczywiście. Zależnie od wybranej technologii oraz stanu początkowego Twojego dachu, udzielamy pisemnej gwarancji od 5 do nawet 20 lat na szczelność nałożonej powłoki." },
  { q: "Czy przed hydroizolacją natryskową trzeba zrywać starą papę?", a: "W 90% przypadków nie ma takiej potrzeby. Nasze systemy są zaprojektowane tak, aby tworzyć bezspoinową, elastyczną warstwę bezpośrednio na starym podłożu. To oszczędza Twój czas, nerwy i pieniądze potrzebne na kosztowną utylizację papy." },
  { q: "Jakie są przewagi malowania hydrodynamicznego nad wałkiem?", a: "To przede wszystkim czas (nawet 10-krotnie szybciej), idealnie gładka struktura bez smug czy śladów po wałku oraz możliwość dotarcia do najdrobniejszych zakamarków i porów na elewacjach czy trudnych strukturach dachowych." },
  { q: "Czy malujecie i kładziecie gładzie tylko na zewnątrz?", a: "Nie. Nasz nowoczesny park maszynowy pozwala nam na wykonywanie gładzi polimerowych i malowania hydrodynamicznego wewnątrz budynków (domy jednorodzinne, biura, obiekty użyteczności publicznej)." },
  { q: "Kiedy najlepiej zarezerwować termin realizacji?", a: "Ze względu na sezonowość branży budowlanej (prace zewnętrzne są silnie uzależnione od pogody), zachęcamy do kontaktu z 1-2 miesięcznym wyprzedzeniem. Zdarzają się jednak okienka w grafiku, więc warto pytać o wolne terminy na bieżąco!" }
];

export const opinionsData: Opinion[] = [
  { text: "Pełen profesjonalizm! Pan Przemek z firmy HydroPAKiet doradził najlepsze rozwiązanie do naszego dachu. Mycie i impregnacja wykonane błyskawicznie, a dom wygląda jak nowy. Bardzo polecam współpracę z natryskujemy.pl!", author: "Michał T., Tarnowskie Góry" },
  { text: "Zleciłem im malowanie hydrodynamiczne sporej hali magazynowej. Byłem w szoku, w jakim tempie to zrobili. Zero zacieków, idealne krycie. Konkretna firma, rzetelna wycena i super kontakt.", author: "Tomasz W., Bytom" },
  { text: "Gładzie natryskowe to był strzał w dziesiątkę. Ekipa weszła, zabezpieczyła wszystko i po kilku dniach ściany były gładkie jak szkło. Zero pyłu latającego po całym domu i szybka realizacja.", author: "Anna K., Gliwice" },
  { text: "Mieliśmy problem z przeciekającym płaskim dachem przez dwa sezony. Dopiero powłoka od natryskujemy.pl rozwiązała sprawę definitywnie. Solidni fachowcy, po których widać doświadczenie.", author: "Piotr M., Zabrze" }
];

export const projectsData: Project[] = [
  { id: 1, category: 'hydroizolacje', iconName: 'ShieldCheck', title: "Hydroizolacja Dachu Płaskiego (Papa)", location: "Tarnowskie Góry", image: "https://images.unsplash.com/photo-1621648057993-9c59577c3857?auto=format&fit=crop&q=80", stats: { area: "450 m²", time: "2 dni", guarantee: "15 lat" }, problem: "Rozległe przecieki wierzchniej warstwy starej papy termozgrzewalnej, powodujące zawilgocenie poddasza użytkowego.", solution: "Oczyszczenie dachu, aplikacja gruntu oraz natrysk elastycznej powłoki bezspoinowej, tworzącej 100% barierę wodną." },
  { id: 2, category: 'malowanie', iconName: 'PaintRoller', title: "Malowanie Hali Przemysłowej", location: "Katowice", image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80", stats: { area: "1200 m²", time: "3 dni", type: "Antykorozja" }, problem: "Złuszczająca się farba na konstrukcji stalowej hali i konieczność szybkiego odświeżenia wnętrza.", solution: "Dokładne mycie pod ciśnieniem oraz błyskawiczne malowanie agregatem hydrodynamicznym specjalistyczną farbą." },
  { id: 3, category: 'gladzie', iconName: 'Layers', title: "Gładzie Polimerowe na Osiedlu", location: "Gliwice", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80", stats: { area: "850 m²", time: "5 dni", type: "Polimerowe" }, problem: "Nierówne tynki deweloperskie w nowo wybudowanych domach szeregowych.", solution: "Zastosowanie gładzi polimerowych nanoszonych agregatem. Natrysk pozwolił na uzyskanie idealnej tafli." },
  { id: 4, category: 'hydroizolacje', iconName: 'ShieldCheck', title: "Renowacja Tarasu (Membrana)", location: "Rybnik", image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80", stats: { area: "120 m²", time: "1 dzień", guarantee: "10 lat" }, problem: "Pękające płytki i przecieki do pomieszczenia bezpośrednio pod tarasem po mroźnym okresie zimowym.", solution: "Aplikacja trwałej membrany poliuretanowej bezpośrednio na stare płytki. Brak konieczności głośnego i drogiego kucia." },
  { id: 5, category: 'malowanie', iconName: 'PaintRoller', title: "Odświeżenie Elewacji Magazynu", location: "Dąbrowa Górnicza", image: "https://images.unsplash.com/photo-1504307651254-35680f35aa9e?auto=format&fit=crop&q=80", stats: { area: "2500 m²", time: "4 dni", type: "Fasada" }, problem: "Wyblakła i silnie zabrudzona elewacja przemysłowa z płyt warstwowych, która psuła rynkowy wizerunek firmy.", solution: "Dogłębne mycie wysokociśnieniowe oraz dwukrotne malowanie natryskowe wydajnym agregatem z użyciem farby fasadowej." },
  { id: 6, category: 'gladzie', iconName: 'Layers', title: "Gładzie w Nowym Biurowcu", location: "Chorzów", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80", stats: { area: "1800 m²", time: "8 dni", type: "Gipsowe" }, problem: "Krótki termin oddania budynku do użytku i konieczność natychmiastowego, gładkiego przygotowania ścian pod malowanie.", solution: "Zastosowanie wydajnych agregatów do gładzi i zgranej ekipy, co pozwoliło nam wyprzedzić napięty harmonogram inwestora o całe 3 dni." }
];